/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

/**
 *
 * @author Pichau
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form AgendaRolagem
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabelObservacao = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        TextObservacao = new javax.swing.JTextField();
        TextHora = new javax.swing.JTextField();
        TextData = new javax.swing.JTextField();
        TextValor = new javax.swing.JTextField();
        jTextID = new javax.swing.JTextField();
        jComboBoxServico = new javax.swing.JComboBox();
        jComboBoxCliente = new javax.swing.JComboBox();
        jLabelHora = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelServico = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        TextObservacao1 = new javax.swing.JTextField();
        TextObservacao2 = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        TextHora1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "EDUARDO", "SÓ CORTE", "10:00", "Ligar"},
                {"2", "JOÃO", "SÓ BARBA", "11:00", ""},
                {"3", "HENRIQUE", "COMPLETO", "9:00", "Cortar c/ Edu"},
                {"4", null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Serviço", "Hora", "Observação"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, 1040, 170));

        jLabelObservacao.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservacao.setText("Observação");
        jPanel1.add(jLabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, -1, -1));

        jToggleButton1.setBackground(new java.awt.Color(51, 255, 102));
        jToggleButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jToggleButton1.setText("Agendar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 340, 40));

        TextObservacao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TextObservacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextObservacaoActionPerformed(evt);
            }
        });
        jPanel1.add(TextObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 250, 400, 260));

        TextHora.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHoraActionPerformed(evt);
            }
        });
        jPanel1.add(TextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 360, 60));

        TextData.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextDataActionPerformed(evt);
            }
        });
        jPanel1.add(TextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 360, 60));

        TextValor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValorActionPerformed(evt);
            }
        });
        jPanel1.add(TextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 360, 60));

        jTextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 360, 60));

        jComboBoxServico.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jComboBoxServico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SÓ CORTE", "SÓ BARBA", "COMPLETO" }));
        jComboBoxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicoActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 360, 60));

        jComboBoxCliente.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EDUARDO", "JOÃO", "FLÁVIO", "JOSÉ", "HENRIQUE" }));
        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 360, 60));

        jLabelHora.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHora.setText("Hora");
        jPanel1.add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 60, 30));

        jLabelData.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelData.setForeground(new java.awt.Color(255, 255, 255));
        jLabelData.setText("Data");
        jPanel1.add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, 30));

        jLabelValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Valor R$");
        jPanel1.add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 100, 30));

        jLabelServico.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelServico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelServico.setText("Serviço");
        jPanel1.add(jLabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, 30));

        jLabelCliente.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCliente.setText("Cliente");
        jPanel1.add(jLabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 80, 30));

        jLabelID.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID.setText("ID");
        jPanel1.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 950));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AgendaFundo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 990));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Observação");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, -1, -1));

        jToggleButton2.setBackground(new java.awt.Color(51, 255, 102));
        jToggleButton2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jToggleButton2.setText("Agendar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 340, 40));

        TextObservacao1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TextObservacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextObservacao1ActionPerformed(evt);
            }
        });
        jPanel1.add(TextObservacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 250, 400, 260));

        TextObservacao2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TextObservacao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextObservacao2ActionPerformed(evt);
            }
        });
        jPanel1.add(TextObservacao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 250, 400, 260));

        jToggleButton3.setBackground(new java.awt.Color(51, 255, 102));
        jToggleButton3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jToggleButton3.setText("Agendar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 340, 40));

        TextHora1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        TextHora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextHora1ActionPerformed(evt);
            }
        });
        jPanel1.add(TextHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 360, 60));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void TextObservacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextObservacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextObservacaoActionPerformed

    private void TextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextHoraActionPerformed

    private void TextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextDataActionPerformed

    private void TextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValorActionPerformed

    private void jTextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDActionPerformed

    private void jComboBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServicoActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void TextObservacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextObservacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextObservacao1ActionPerformed

    private void TextObservacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextObservacao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextObservacao2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void TextHora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextHora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextHora1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextData;
    private javax.swing.JTextField TextHora;
    private javax.swing.JTextField TextHora1;
    private javax.swing.JTextField TextObservacao;
    private javax.swing.JTextField TextObservacao1;
    private javax.swing.JTextField TextObservacao2;
    private javax.swing.JTextField TextValor;
    private javax.swing.JComboBox jComboBoxCliente;
    private javax.swing.JComboBox jComboBoxServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelServico;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextID;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
